[package]
name = "deployer"
version = "0.1.0"
edition = "2024"

[dependencies]
rocket = { version = "0.5.1", features = ["json"] }
serde = "1.0.202"
serde_json = "1.0.117"

[dependencies.rocket_dyn_templates]
version = "0.1.0"
features = ["tera"]